// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 18-3-2025 13:38:14
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/plugins/**/*.{js,ts,mjs}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/composables/**/*.{js,ts,mjs}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/utils/**/*.{js,ts,mjs}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jelmerbouman/Documents/devWorkspace/ArtPortfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;